### PR TITLE
AENV-518: image width in pixel is calculated based on width of the choosen viewport

### PR DESCRIPTION
**Pull request by thnkloud9**
update Article service serialize function to match images and snippets in child divs of pasted content.

This is not particularly pretty, or well thought out, but it solves the issue for now.  Please let me know if you can think of a better way to resolve the issue.  Or any feedback really.

### CODE REVIEW

**Comment by ahilles107** [comment]
:+1:

**Comment by plamut** [comment]
The tests need to be added, as always. :wink:

**Comment by takeit** [comment]
@thnkloud9 looks like we missed to merge this one. How about the tests ?

**Comment by thnkloud9** [comment]
yeah, this is another tricky one because its a directive.  I'm still working on the test.

**Pull request merged**
