### PR TITLE
WIP: AENV-224: save button and toolbar icons are being disabled in ff 30.0

### PR DESCRIPTION
**Pull request by thnkloud9**
fixed by manually setting alohaEditable based on range selection, and triggering "aloha-smart-content-changed" event manually.  Still not sure why these are not handled by Aloha internally for FF though.

### CODE REVIEW

**Comment by takeit** [comment]
pls check travis logs, IE 11.0.0 (Windows 8.1 0.0.0) Directive: sfAlohaFormatGeneric called the correct Aloha.execCommand FAILED

**Comment by thnkloud9** [comment]
is it possible to turn off automated testing for IE?  There will probably be a lot of test that fail there, and I don't think we are really officially supporting it.

**Comment by takeit** [comment]
yes, it's possible in karma.js file. Scoopwriter supports IE10+ (https://github.com/newscoop/JS-Scoopwriter#browser-compatibility), according to tests. All tests were passing on IE 10+ so far, so I don't think it's a good idea to disable it at all

**Comment by thnkloud9** [comment]
Leaving this change out for now until the IE issues can be sorted.

**Pull request closed without merging**
